# Generated by Django 6.0.1 on 2026-01-22 15:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(default=core.models.default_expires_at),
        ),
    ]
