# Generated by Django 6.0.1 on 2026-01-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_booking_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
