# Generated by Django 6.0.1 on 2026-01-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_booking_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('service_type', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0)),
                ('about', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('place_id', models.CharField(max_length=255)),
                ('accuracy', models.IntegerField()),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='core.master')),
            ],
        ),
        migrations.CreateModel(
            name='MasterAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_slots', models.JSONField()),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.master')),
            ],
            options={
                'unique_together': {('master', 'date')},
            },
        ),
    ]
