# Generated by Django 6.0.1 on 2026-02-05 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_guestprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='master',
            name='service_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='master',
            name='service_type',
            field=models.CharField(choices=[('barber', 'Barber'), ('beard', 'Beard'), ('haircut', 'Haircut'), ('planting', 'Planting')], default='barber', max_length=20),
        ),
        migrations.AlterField(
            model_name='masterlocation',
            name='master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_location', to='core.master'),
        ),
    ]
