# Generated by Django 6.0.1 on 2026-02-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_master_price_master_service_types_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramProfile',
        ),
    ]
