# Generated by Django 6.0.1 on 2026-02-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_telegramprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='platform',
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
